# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TsXgLgWD6eLZE5cErtPVO2ihoHnox13d
"""

# langchain-google-genai 패키지 설치
# !pip install -q langchain langchain-google-genai langgraph
# word 파일 읽어오기 위한 패키지 설치
# !pip install -q python-docx langchain langchain-google-genai langgraph

import streamlit as st
import os
import docx
from typing import TypedDict
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import StateGraph, END

# ==========================================
# 1. 기본 설정 & 비밀키 로드
# ==========================================
st.set_page_config(page_title="AI 커리어 코치 (정밀분석)", page_icon="🎯", layout="wide")

# API 키 로드 (Streamlit Secrets)
if "GOOGLE_API_KEY" in st.secrets:
    os.environ["GOOGLE_API_KEY"] = st.secrets["GOOGLE_API_KEY"]
else:
    st.error("🚨 API 키가 없습니다. Streamlit Secrets 설정을 확인하세요.")
    st.stop()

# 모델 설정
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0)

# ==========================================
# 2. 로직 함수 (파서 삭제됨 -> 심플해짐)
# ==========================================

# (1) 이력서 파일 읽기
def read_resume_file(uploaded_file):
    try:
        doc = docx.Document(uploaded_file)
        full_text = []
        for para in doc.paragraphs:
            if para.text.strip():
                full_text.append(para.text)
        for table in doc.tables:
            for row in table.rows:
                row_text = [cell.text for cell in row.cells if cell.text.strip()]
                if row_text:
                    full_text.append(" | ".join(row_text))
        return "\n".join(full_text)
    except Exception as e:
        return f"이력서 읽기 실패: {e}"

# (2) 상태 정의 (이제 파싱된 결과가 아니라, 입력 자체가 분리됨)
class AgentState(TypedDict):
    resume_text: str       # 내 이력서
    duties: str            # 주요 업무
    requirements: str      # 자격 요건
    preferred: str         # 우대 사항
    final_result: str      # 결과

# (3) 매칭 노드 (바로 비교 시작!)
def match_node(state: AgentState):
    prompt = ChatPromptTemplate.from_template("""
    당신은 20년 경력의 베테랑 IT 채용 담당자입니다.
    지원자의 이력서를 채용공고의 3대 요소와 정밀 대조하여 평가하세요.

    ---
    [📂 지원자 이력서]
    {resume}

    [🏢 목표 채용공고]
    1. 📌 주요 업무 (Duties):
    {duties}

    2. ⚠️ 자격 요건 (Must-Have):
    {requirements}

    3. 🌟 우대 사항 (Nice-to-Have):
    {preferred}

    ---
    **분석 결과 리포트:**

    1. 📊 **적합도 점수**: OO점 / 100점
       - (감점 요인과 가산점 요인을 명확히 근거로 제시)

    2. ✅ **합격 포인트 (Matching)**:
       - 지원자가 완벽하게 충족하는 요건

    3. 🚨 **보완 필요 사항 (Gap Analysis)**:
       - 자격요건 중 부족한 부분 (치명적)
       - 우대사항 중 놓친 부분 (경쟁력 약화)

    4. 💡 **필승 전략 및 추천 프로젝트**:
       - 부족한 부분을 메우기 위해 [어떤 기술]을 사용하여 [어떤 미니 프로젝트]를 해야 하는지 구체적으로 제안.
    """)

    chain = prompt | llm
    response = chain.invoke({
        "resume": state['resume_text'],
        "duties": state['duties'],
        "requirements": state['requirements'],
        "preferred": state['preferred']
    })

    return {"final_result": response.content}

# (4) 그래프 연결 (파서가 사라져서 아주 단순해짐)
workflow = StateGraph(AgentState)
workflow.add_node("matcher", match_node) # 노드가 하나뿐!
workflow.set_entry_point("matcher")      # 바로 시작
workflow.add_edge("matcher", END)        # 바로 끝
app = workflow.compile()

# ==========================================
# 3. UI 구성 (입력창 3개로 분리)
# ==========================================
st.title("🎯 AI 취업 비서: 채용공고 정밀 분석기")
st.markdown("채용공고를 항목별로 나누어 입력하면 AI가 더 정확하게 분석합니다.")

col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("1️⃣ 내 이력서 (Word)")
    uploaded_file = st.file_uploader("파일 업로드", type=["docx"])

    st.markdown("---")
    st.subheader("2️⃣ 채용공고 입력")

    # 입력창 3개 배치
    duties_input = st.text_area("📌 주요 업무 (담당할 일)", height=100, placeholder="예: LLM 모델 서빙, 데이터 파이프라인 구축...")
    req_input = st.text_area("⚠️ 자격 요건 (필수)", height=100, placeholder="예: Python 능숙자, Docker 사용 경험...")
    pref_input = st.text_area("🌟 우대 사항 (가산점)", height=100, placeholder="예: LangChain 프로젝트 경험, 오픈소스 기여...")

    run_btn = st.button("🚀 정밀 분석 시작", type="primary", use_container_width=True)

with col2:
    st.subheader("3️⃣ 분석 결과")
    if run_btn:
        if not uploaded_file:
            st.warning("이력서 파일을 먼저 업로드해주세요.")
        elif not duties_input and not req_input: # 최소한 업무나 자격요건은 있어야 함
            st.warning("주요 업무와 자격 요건을 입력해주세요.")
        else:
            with st.spinner("AI가 채용 담당자의 눈으로 분석 중입니다..."):
                # 파일 읽기
                resume_text = read_resume_file(uploaded_file)

                # 그래프 실행 (쪼개진 데이터를 그대로 전달)
                result = app.invoke({
                    "resume_text": resume_text,
                    "duties": duties_input,
                    "requirements": req_input,
                    "preferred": pref_input
                })

                # 결과 출력
                st.markdown(result['final_result'])
                st.success("분석이 완료되었습니다!")